language: groovy
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  - ./gradlew check sonarqube
addons:
  hostname: travis-ci
after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && ./gradlew release build uploadArchives"
