language: groovy
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  - ./gradlew check codenarc
addons:
  hostname: travis-ci
after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && ./gradlew release build uploadArchives"
after_script:
  - sudo keytool -import -alias sonar -keystore $JAVA_HOME/jre/lib/security/cacerts -file sonar_cert.pem -storepass changeit -noprompt
  # Check if commit is not a pull request, if git repo is official, and if branch is master. If checks pass, run Sonar reports
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == figurate/figurate-gradle ]] && [[ $TRAVIS_BRANCH == master ]] && ./gradlew sonarqube"
  
